/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoregistroads;
import java.sql.Connection;
import java.awt.Font;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.awt.Toolkit;

/**
 *
 * @author Lucas
 */
public class Registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        
        //Adicionei uma fonte externa.
        try {
            InputStream is = getClass().getResourceAsStream("/projetoregistroads/PlayfairDisplay-Bold.ttf");
            Font fonteTitulo = Font.createFont(Font.TRUETYPE_FONT, is).deriveFont(36f);
            
            EntrarTitulo.setFont(fonteTitulo);
            
        } catch (Exception e) {
            System.err.println("Erro ao carregar a fonte!");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Esquerdo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Direito = new javax.swing.JPanel();
        EntrarTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome_completo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        novo = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRequisitos = new javax.swing.JMenu();
        menuDesenvolvedor = new javax.swing.JMenu();
        menuVersao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 248, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Esquerdo.setBackground(new java.awt.Color(55, 145, 166));
        Esquerdo.setForeground(new java.awt.Color(55, 145, 166));
        Esquerdo.setMinimumSize(new java.awt.Dimension(400, 500));
        Esquerdo.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_resort.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel4ComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout EsquerdoLayout = new javax.swing.GroupLayout(Esquerdo);
        Esquerdo.setLayout(EsquerdoLayout);
        EsquerdoLayout.setHorizontalGroup(
            EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EsquerdoLayout.setVerticalGroup(
            EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EsquerdoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Esquerdo);
        Esquerdo.setBounds(0, 0, 400, 500);

        Direito.setBackground(new java.awt.Color(250, 248, 241));
        Direito.setPreferredSize(new java.awt.Dimension(400, 500));

        EntrarTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        EntrarTitulo.setForeground(new java.awt.Color(93, 64, 55));
        EntrarTitulo.setText("CADASTRAR");

        jLabel1.setBackground(new java.awt.Color(55, 145, 166));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 64, 55));
        jLabel1.setText("ID");

        txtID.setBackground(new java.awt.Color(250, 248, 241));
        txtID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 64, 55)));
        txtID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(55, 145, 166));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 64, 55));
        jLabel2.setText("Nome Completo");

        nome_completo.setBackground(new java.awt.Color(250, 248, 241));
        nome_completo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nome_completo.setForeground(new java.awt.Color(0, 0, 0));
        nome_completo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 64, 55)));
        nome_completo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_completoActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(55, 145, 166));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(93, 64, 55));
        jLabel3.setText("E-mail");

        txtEMAIL.setBackground(new java.awt.Color(250, 248, 241));
        txtEMAIL.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEMAIL.setForeground(new java.awt.Color(0, 0, 0));
        txtEMAIL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 64, 55)));
        txtEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEMAILActionPerformed(evt);
            }
        });

        salvar.setBackground(new java.awt.Color(0, 39, 77));
        salvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        salvar.setForeground(new java.awt.Color(255, 255, 255));
        salvar.setText("SALVAR");
        salvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 15, true));
        salvar.setBorderPainted(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        novo.setBackground(new java.awt.Color(0, 39, 77));
        novo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        novo.setForeground(new java.awt.Color(255, 255, 255));
        novo.setText("NOVO");
        novo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        novo.setBorderPainted(false);
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(250, 248, 241));
        botaoSair.setForeground(new java.awt.Color(93, 64, 55));
        botaoSair.setText("SAIR");
        botaoSair.setBorderPainted(false);
        botaoSair.setMaximumSize(new java.awt.Dimension(43, 18));
        botaoSair.setMinimumSize(new java.awt.Dimension(43, 18));
        botaoSair.setPreferredSize(new java.awt.Dimension(43, 18));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DireitoLayout = new javax.swing.GroupLayout(Direito);
        Direito.setLayout(DireitoLayout);
        DireitoLayout.setHorizontalGroup(
            DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DireitoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DireitoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(EntrarTitulo))
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nome_completo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(DireitoLayout.createSequentialGroup()
                            .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DireitoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        DireitoLayout.setVerticalGroup(
            DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DireitoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(EntrarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_completo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(Direito);
        Direito.setBounds(400, 0, 400, 500);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleName("REGISTRO");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.setBackground(new java.awt.Color(0, 39, 77));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorderPainted(false);

        menuRequisitos.setForeground(new java.awt.Color(255, 255, 255));
        menuRequisitos.setText("Requisitos");
        menuRequisitos.setToolTipText("<html>Requisitos mínimos: Java 25. </html>");
        menuRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRequisitosActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuRequisitos);

        menuDesenvolvedor.setForeground(new java.awt.Color(255, 255, 255));
        menuDesenvolvedor.setText("Desenvolvedor");
        menuDesenvolvedor.setToolTipText("<html>Software desenvolvido por: <b>Lucas Oliveira Franco</b>.<br>Projeto para a disciplina Linguagem de Programação.</html>");
        menuDesenvolvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesenvolvedorActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuDesenvolvedor);

        menuVersao.setForeground(new java.awt.Color(255, 255, 255));
        menuVersao.setText("Versão");
        menuVersao.setToolTipText("<html>Pousada Francos - Sistema de Cadastro.<br>Versão 1.0.0 (Outubro 2025)</html>");
        jMenuBar1.add(menuVersao);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        //fecha o programa ao clicar no botão sair
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        //código do botão NOVO, apaga o que está digitado.
        txtID.setText("");
        nome_completo.setText("");
        txtEMAIL.setText("");
        //arrasta o cursor para o campo ID
        txtID.requestFocus();
    }//GEN-LAST:event_novoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        //código do botão salvar
        String id = txtID.getText();
        String nome = nome_completo.getText();
        String email = txtEMAIL.getText();
        
        id = id.trim();
        id = id.replaceAll("\\s","");
                
        if(!id.matches("\\d{6}")){
            JOptionPane.showMessageDialog(this,
                    "O ID está inválido!\nEle deve conter 6 números.",
                    "ERRO DE VALIDAÇÃO",
                    JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            return;
        }
        
        if(nome.trim().isEmpty() || !nome.matches("[a-zA-ZÀ-ÿ\\s]+")) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, insira um nome.",
                    "ERRO DE VALIDAÇÃO",
                    JOptionPane.ERROR_MESSAGE);
            nome_completo.requestFocus();
            return;
        }
        
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if(!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this,
                    "O formato do e-mail está inválido",
                    "ERRO DE VALIDAÇÃO",
                    JOptionPane.ERROR_MESSAGE);
            txtEMAIL.requestFocus();
            return;
        }
        
        //banco de dados
        String url, user, senha, sql;
        url = "jdbc:mysql://sql10.freesqldatabase.com:3306/sql10802255";
        user = "sql10802255";
        senha = "RyLccumyJp";
        sql = "INSERT INTO cliente (id, nome_completo, email) VALUES (?, ?, ?)";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        }           catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        
        try (Connection conn = DriverManager.getConnection(url, user, senha);
            PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, Integer.parseInt(id));
            stmt.setString(2, nome);
            stmt.setString(3, email);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Seu cadastro foi um sucesso!");
            novoActionPerformed(evt);
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados!\n" + e.getMessage(),
                    "ERRO BANCO DE DADOS",
                    JOptionPane.ERROR_MESSAGE);
                
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "O ID não é um número válido!\n" + e.getMessage(),
                    "ERRO ID INVÄLIDO",
                    JOptionPane.ERROR_MESSAGE);
                }
            
    }//GEN-LAST:event_salvarActionPerformed

    private void txtEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEMAILActionPerformed

    private void nome_completoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_completoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_completoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jLabel4ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel4ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4ComponentHidden

    private void menuRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRequisitosActionPerformed
 
    }//GEN-LAST:event_menuRequisitosActionPerformed

    private void menuDesenvolvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesenvolvedorActionPerformed
 
    }//GEN-LAST:event_menuDesenvolvedorActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isWhitespace(c)) {
            evt.consume();
            return;
        }
        
        if(!Character.isDigit(c)) {
            evt.consume();
            return;
        }
        
        if(txtID.getText().length() >= 6) {
            evt.consume();
        }
                           
    }//GEN-LAST:event_txtIDKeyTyped

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Direito;
    private javax.swing.JLabel EntrarTitulo;
    private javax.swing.JPanel Esquerdo;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuDesenvolvedor;
    private javax.swing.JMenu menuRequisitos;
    private javax.swing.JMenu menuVersao;
    private javax.swing.JTextField nome_completo;
    private javax.swing.JButton novo;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
